# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 10:29
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180116_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='위도, 경도 포맷으로 입력', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
