# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180116_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
