# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('w', 'Withdrawn')], max_length=1),
        ),
    ]
